### PR TITLE
R2000 fix

### LINKED ISSUE #9: R2000 Driver produces corrupt data under high load
We experienced an issue during field testing a week ago where the system was unable to keep up with the log data rate for whatever reason, and this appears to have led to corrupt data logged from the R2000 sensor attached.  *Missing* data would obviously be expected if the system is unable to keep up, however in this case it appears that data is incorrectly assigned to points in the wrong laserscan or something, leading to things like the ground plane of the scan being duplicated and mis-aligned.

I haven't had time to reproduce this in the lab yet, but it appears to me that the current driver code (e.g. [here](https://github.com/PepperlFuchs/ROS_driver/blob/master/pf_driver/include/pf_driver/pf_interface.hpp#L105)) doesn't do any validation that packets are arriving and being parsed in order without missing packets, and so if packets are out of order or dropped, the subsequent scan points end up being incorrectly assigned to the wrong angular slots in a ScanData object.  I am hoping to have time later this afternoon to do some further testing of this in the office.

Of interest: the R2300 we were logging at the same time doesn't appear to have any issues with corrupt data - unclear to me exactly why that is; maybe each scan fits entirely in one packet or something?

### PR DESCRIPTION
**Pull request by bk-mtg**
Several fixes to get this working with the R2000 sensor I have (more details in individual commit messages):
- Actually publish amplitudes in the LaserScan messages
- Re-enable parsing of packet type B data
- Support non-default packet type and use packet type C instead of A on R2000 (no change to R2300)
- Fix/workaround for (I assume?) older lidar that's using a shorter packet header than the latest PFSDP spec
- Fix for streaming data over TCP (where one PFSDP packet != one TCP packet)

### CODE REVIEW

**Comment by ipa-hsd** [comment]
@bk-mtg thanks for your contribution! I will go through the comments in the coming days and get back. Nice work!

File: pf_driver/src/ros/scan_publisher.cpp [hunk 1]
```diff
@@ -83,6 +85,8 @@ void ScanPublisher::to_msg_queue(T &packet, uint16_t layer_idx)
         else
             data = packet.distance[i] / 1000.0;
         msg->ranges[idx + i] = std::move(data);
+        if(packet.amplitude[i] >= 32 && !std::is_same<T,PFR2000Packet_A>::value)
```
Comment (ipa-hsd) [inline pf_driver/src/ros/scan_publisher.cpp:88]: I am not comfortable checking for a specific packet type (`std::is_same<T,PFR2000Packet_A>::value`). Instead we could check for size of intensities 
```
if(!packet.amplitude.empty() && packet.amplitude[i] >= 32)
```

File: pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp [hunk 2]
```diff
@@ -362,9 +367,13 @@ class PFSDPBase
     return handle_info;
   }
 
-  virtual HandleInfo request_handle_udp(const std::string host_ip, const std::string port)
+  virtual HandleInfo request_handle_udp(const std::string host_ip, const std::string port, const std::string packet_type = "")
   {
-    auto resp = get_request("request_handle_udp", { "handle", "port" }, { KV("address", host_ip), KV("port", port) });
+    param_map_type query = { KV("address", host_ip), KV("port", port) };
```
Comment (ipa-hsd) [inline pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp:372]: Might make sense to add some tests later to check for validity of requests URI.

File: pf_driver/src/pf/pf_interface.cpp [hunk 3]
```diff
@@ -98,7 +93,7 @@ bool PFInterface::start_transmission()
 
         std::string host_ip = transport_->get_host_ip();
         port_ = transport_->get_port();
-        info_ = protocol_interface_->request_handle_udp(host_ip, port_);
+        info_ = protocol_interface_->request_handle_udp(host_ip, port_, pkt_type);
```
Comment (ipa-hsd) [inline pf_driver/src/pf/pf_interface.cpp:96]: The API was changed in previous commit https://github.com/PepperlFuchs/ROS_driver/pull/26/commits/4ad6e9e9c6bbbd12ccc55385545b74df66216f49. It would be better to make that API change here to keep it together. It is a bit confusing the current way.

File: pf_driver/src/pf/pf_packet.cpp [hunk 4]
```diff
@@ -14,7 +14,7 @@ bool PFPacket::parse_buf(uint8_t* buf, size_t buf_len, size_t &remainder, size_t
     std::tie(h_size, p_size, num) = read_header(stream);
 
     auto data_size = p_size - h_size;
-    if((buf_len - SIZE) < data_size)
+    if(buf_len < p_size)
```
Comment (ipa-hsd) [inline pf_driver/src/pf/pf_packet.cpp:17]: This comment concerns me:
```
so we'll end up with some header fields that might be invalid (with no indication to the user)
```
Also I wanted to move all the parsing related checks in `pf_parser.h`. Because that is what the parser class was supposed to do. This commit might be a good place to do that.

File: pf_driver/include/pf_driver/pf/writer.h [hunk 5]
```diff
@@ -36,12 +36,21 @@ class PFWriter : public Writer<T>
...
     virtual bool get(std::vector<std::unique_ptr<T>> &packets)
     {
-        // uint8_t buf[4096];
         boost::array<uint8_t, 4096> buf;
         size_t read = 0;
+        size_t used = 0;
         if(transport_->read(buf, read))
         {
-            parser_->parse(buf.data(), read, packets);
+            persistent_buffer_.insert(persistent_buffer_.end(), buf.begin(), buf.begin() + read);
```
Comment (ipa-hsd) [inline pf_driver/include/pf_driver/pf/writer.h:44]: I like the idea of using persistence here!

**Comment by ipa-hsd** [comment]
Again, nice work and thanks for the contribution! I have added some comments.

File: pf_driver/src/ros/scan_publisher.cpp (hunk 1 above)
Comment (bk-mtg) [reply pf_driver/src/ros/scan_publisher.cpp:88]: Makes sense.  Are you okay with referring to the specific packet type above?
https://github.com/PepperlFuchs/ROS_driver/blob/9a60a7c3a08901b55744813d20b7a9ab86524215/pf_driver/src/ros/scan_publisher.cpp#L67-L68

File: pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp (hunk 2 above)
Comment (bk-mtg) [reply pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp:372]: I assume that will be a different PR...

File: pf_driver/src/pf/pf_interface.cpp (hunk 3 above)
Comment (bk-mtg) [reply pf_driver/src/pf/pf_interface.cpp:96]: I kinda liked it this way, but it's your repo, so... change incoming.

File: pf_driver/src/pf/pf_packet.cpp (hunk 4 above)
Comment (bk-mtg) [reply pf_driver/src/pf/pf_packet.cpp:17]: WRT the comment about header fields being invalid, any thoughts on how you *would* like to handle that?  I guess it seems to me like there are basically four options:
1. Since those header fields simply aren't supplied by the sensor, their value won't have meaning anyway, and we don't worry too much about what value ends up in them.  (this is the current approach)
2. Those header fields should be set to zero value.  This at least avoids giving the user the impression that the fields are somehow working or weirdly broken (because they have changing data in them), but doesn't necessarily make it obvious to the user that the fields *aren't* working.  This approach would probably be reasonably easy by zeroing portions of the header before passing it to `ros::serialization`.
3. Fill fields with a non-zero value that indicates "no data" (not sure if there is even such a value).  This gets much harder because we then end up duplicating work that's being done now in ros serialization in order to figure out *which* header fields need this special value.
4. There might be some way to alter the header in realtime to indicate that these types aren't even present, but again, that seems like it becomes even more specialized, and might necessitate further conditionals in code that uses the header data, since it would then have to check packet types or header presence or something.

I guess I'd say either option 1 (as is) or option 2 (easy change to zero part of a buffer).

Comment (bk-mtg) [reply pf_driver/src/pf/pf_packet.cpp:17]: WRT moving parsing checks to `pf_parser.h`, I'm not sure how much more makes sense to do there.  I see four checks total:
1. (in parser) check that the buffer has at least enough bytes for a header
2. (in parser) check that the packet starts with the right magic number
3. (in `packet.parse_buf`) check that the buffer has at least enough bytes for the full packet
4. (in `packet.parse_buf`) check that the buffer has at least enough bytes for all the data points expected

Checks 3 and 4 are kinda redundant (and 4 currently assumes 32 bits per point, which isn't right for packet type B), so I'd personally be inclined to drop check 4 altogether.

Check 3 is currently being done here because it requires having parsed the packet header to know how many bytes are *supposed* to be in the packet.  I guess technically, parsing the packet header could be moved to the `pf_parser.h`, but if so, we might as well move this entire function to `pf_parser.h`, since it would only be four lines long at that point.

I guess that's a long way of saying that I'd be inclined to leave this check in `packet.parse_buf` and maybe delete the fourth check about number of points.

**Comment by bk-mtg** [comment]
I've pushed some additional updates that address several of your comments; I think there's one comment left that I had some questions on, so waiting to hear back your thoughts on those to make further changes.

As in the other PR, I can verify that these changes compile, but I no longer have an R2000 to test against real hardware.

File: pf_driver/src/ros/scan_publisher.cpp (hunk 1 above)
Comment (ipa-hsd) [reply pf_driver/src/ros/scan_publisher.cpp]: This line can be removed (?) so that `amplitude` is empty:
https://github.com/PepperlFuchs/ROS_driver/blob/64e3620341323e6fac48a3259e5de55feeb60a87/pf_driver/src/pf/pf_packet.cpp#L55
And you could check this:
```
if(!packet.amplitude.empty() && packet.amplitude[i] >= 32)
```
So that we are not referring to any specific packet type within the function. Would that be ok?

File: pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp (hunk 2 above)
Comment (ipa-hsd) [reply pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp:372]: Yes

File: pf_driver/src/pf/pf_interface.cpp (hunk 3 above)
Comment (ipa-hsd) [reply pf_driver/src/pf/pf_interface.cpp:96]: > but it's your repo, 

But I am always to new ideas :)

File: pf_driver/src/pf/pf_packet.cpp (hunk 4 above)
Comment (ipa-hsd) [reply pf_driver/src/pf/pf_packet.cpp:17]: > I guess that's a long way of saying that I'd be inclined to leave this check in packet.parse_buf and maybe delete the fourth check about number of points.

Agreed.

**Comment by ipa-hsd** [comment]
@bk-mtg https://github.com/PepperlFuchs/ROS_driver/pull/27 and https://github.com/PepperlFuchs/ROS_driver/pull/29 have been merged. Could you please rebase this PR by pulling in the latest `master` branch? This branch is out-of-date.

File: pf_driver/src/ros/scan_publisher.cpp (hunk 1 above)
Comment (bk-mtg) [reply pf_driver/src/ros/scan_publisher.cpp]: Ah, yeah, I think the bit in `pf_packet.cpp` should do it.

File: pf_driver/src/pf/pf_packet.cpp (hunk 4 above)
Comment (bk-mtg) [reply pf_driver/src/pf/pf_packet.cpp:17]: Okay, deleting the fourth check (enough data for expected number of points).

Still haven't taken any action on possibly invalid header fields.  I was thinking I'd just implement option 2 there (and zero portions of the header before passing to `ros::serialization`, but when I went to do it I realized that the correct header length is one of the parameters we get by deserializing the header, so we might end up doing it twice or something.  Not happy with any of the choices there.

**Comment by bk-mtg** [comment]
Okay, resolved a couple more comments and rebased.  Same caveats as before: I've tested that it builds, but no longer have an R2000 to test against hardware.

**Comment by bk-mtg** [comment]
Oh, I should add: I caught a couple of extra code bugs in my TCP stream parsing code, so I fixed those too (they were places that I was `return`ing out of a while loop instead of `break`ing.  Oops!).

**Comment by ipa-hsd** [comment]
@bk-mtg the commits look good now. Though there seems to some problem with merging for which the branch settings have to changes (I don't have access to that). In the mean time I will check the PR on my device and report back.
